services:
  backend:
    image: cruxsiem/backend:${TAG:-latest}
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    volumes:
      - ./certs/ca.crt:/conf/certs/ca.crt:ro
    networks:
      - cruxsiem-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: cruxsiem/frontend:${TAG:-latest}
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/conf/certs:ro
    depends_on:
      - backend
    networks:
      - cruxsiem-net

networks:
  cruxsiem-net:
    driver: bridge
