heartbeat.monitors:
  - type: http
    id: cruxsiem-webui
    name: "CruxSIEM WebUI"
    urls: ["https://172.16.4.76:443"]
    schedule: '@every 60s'
    timeout: 10s
    ssl:
      verification_mode: none

  - type: http
    id: opensearch-dashboards
    name: "OpenSearch Dashboards"
    urls: ["https://172.16.4.76:5601"]
    schedule: '@every 60s'
    timeout: 10s
    ssl:
      verification_mode: none

  - type: http
    id: kafbat
    name: "Kafbat"
    urls: ["http://172.16.4.76:8080"]
    schedule: '@every 60s'
    timeout: 10s

  - type: tcp
    id: opensearch
    name: "OpenSearch"
    hosts: ["172.16.4.74:9200"]
    schedule: '@every 60s'
    timeout: 10s

  - type: tcp
    id: kafka
    name: "Kafka"
    hosts: ["172.16.4.75:9092"]
    schedule: '@every 60s'
    timeout: 10s

output.kafka:
  hosts: ["pipeline:9092"]
  topic: heartbeat
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

setup.ilm.enabled: false
setup.template.enabled: false

logging.level: info
